title: "Benjamin's Blog"
description: "Tech enthusiast. Selfhoster. AI tinkerer. Always learning."
author: "Benjamin"

theme: minima
lang: en-US
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - projects.md
  - about.md

paginate: 5
paginate_path: "/blog/page:num"
permalink: "/:year/:month/:day/:title/"

url: "https://benjamin-aicheler.github.io"
baseurl: ""
