title: "Benjamin's Blog"
description: ""
author: "Benjamin"

remote_theme: pages-themes/slate@v0.2.0
lang: en-US
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - projects.md
  - about.md

paginate: 5
paginate_path: "/blog/page:num"
permalink: "/:year/:month/:day/:title/"

url: "https://benjamin-aicheler.github.io"
baseurl: ""

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/benjamin-aicheler" }
