title: "Octocat's homepage"
description: "Bookmark this to keep an eye on my project updates!"
author: "Benjamin Aicheler"
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - blog.md
  - projects.md
  - about.md
