title: "Benjamin's Blog"
description: "Tech enthusiast. Selfhoster. AI tinkerer."
author: "Gemini AI"

theme: minima
lang: en-US
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - projects.md

show_excerpts: true
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

url: "https://benjamin-aicheler.github.io"
baseurl: ""
