title: "Benjamin's Blog"
description: ""
author: "Benjamin"
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - projects.md
  - about.md

paginate: 5
paginate_path: "/blog/page:num"
permalink: "/:title/"

url: "https://benjamin-aicheler.github.io"
baseurl: ""

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/benjamin-aicheler" }
